version: '3.8'

services:
  frontend:
    container_name: frontend-service
    build: ./frontend
    ports:
      - '3000:3000'
  backend:
    container_name: backend-service
    build: ./backend
    ports:
      - '8080:8080'
