import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { useEffect, useState } from 'react';
import { NextPage } from 'next/types';

const Home: NextPage = () => {
  const [data, setData] = useState([]);

  useEffect(() => {
    const API_PATH = 'api/getbeer';
    axios.get(API_PATH).then((res: any) => {
      const beers: [] = Array.isArray(res.data.beer) ? res.data.beer : ['no data'];
      setData(beers);
    });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to k8s Sample Application!!(version1.0.1)</h1>

        <p className={styles.description}>
          Response from Backend is.....
          <br />
          <b>{JSON.stringify(data)}</b>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Vercel
        </a>
      </footer>
    </div>
  );
};

export default Home;
